name: dart_lightware
description: A dart library for controlling lightware devices.
version: 1.0.0
homepage: https://github.com/point-source/dart_lightware

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  tcp_client_dart: ^0.2.0

dev_dependencies:
  dart_code_metrics: ^4.19.0
  lints: ^2.0.0
  test: ^1.16.0
